

WIDTH = 1440
HEIGHT = 720

GRID_WIDTH_SIZE = 10
GRID_HEIGHT_SIZE = 10
TOTAL_CELL_QUANTITY = GRID_WIDTH_SIZE * GRID_HEIGHT_SIZE

CELL_SIZE_WIDTH = 2
CELL_SIZE_HEIGHT = CELL_SIZE_WIDTH // 3

RAMDOM_MINE = TOTAL_CELL_QUANTITY // 4