

WIDTH = 1440
HEIGHT = 720

GRID_WIDTH_SIZE = 5
GRID_HEIGHT_SIZE = 5

CELL_SIZE_WIDTH = int(12 - (GRID_HEIGHT_SIZE * 0.5))
CELL_SIZE_HEIGHT = int(CELL_SIZE_WIDTH / 3)

RAMDOM_MINE = int((GRID_HEIGHT_SIZE * GRID_WIDTH_SIZE) * 0.25)