

WIDTH = 1440
HEIGHT = 720

GRID_WIDTH_SIZE = 6
GRID_HEIGHT_SIZE = 6

CELL_SIZE_WIDTH = 12 - (GRID_HEIGHT_SIZE // 2)
CELL_SIZE_HEIGHT = CELL_SIZE_WIDTH // 3

RAMDOM_MINE = (GRID_HEIGHT_SIZE * GRID_WIDTH_SIZE) // 4